#ifndef TINYTEX_VERSION_H
#define TINYTEX_VERSION_H

#define TINYTEX_VERSION_MAJOR 1
#define TINYTEX_VERSION_MINOR 0
#define TINYTEX_VERSION_PATCH 0

#define TINYTEX_VERSION_NUMBER 1

#endif //TINYTEX_VERSION_H
