#include "res/reg/builtin_font_reg.h"

using namespace tex;

DEF_FONT_SET(Builtin)

REG_FONT(msbm10)
REG_FONT(cmex10)
REG_FONT(cmmi10)
REG_FONT(cmmib10)
REG_FONT(moustache)
REG_FONT(cmmi10_unchanged)
REG_FONT(cmmib10_unchanged)
REG_FONT(stmary10)
REG_FONT(cmsy10)
REG_FONT(msam10)
REG_FONT(cmbsy10)
REG_FONT(dsrom10)
REG_FONT(rsfs10)
REG_FONT(eufm10)
REG_FONT(eufb10)
REG_FONT(cmti10)
REG_FONT(cmti10_unchanged)
REG_FONT(cmbxti10)
REG_FONT(cmr10)
REG_FONT(cmss10)
REG_FONT(cmssi10)
REG_FONT(cmtt10)
REG_FONT(cmbx10)
REG_FONT(cmssbx10)
REG_FONT(special)
REG_FONT(r10)
REG_FONT(r10_unchanged)
REG_FONT(ss10)
REG_FONT(si10)
REG_FONT(i10)
REG_FONT(bx10)
REG_FONT(bi10)
REG_FONT(sbi10)
REG_FONT(sb10)
REG_FONT(tt10)

END_DEF_FONT_SET
