INCLUDEPATH += "./latex"

DEFINES += BUILD_QT

SOURCES += \
    latex/samples/qt_texqmlitem.cpp \
    latex/samples/qt_texwidget.cpp \
    latex/atom/atom_basic.cpp \
    latex/atom/atom_impl.cpp \
    latex/atom/box.cpp \
    latex/atom/colors_def.cpp \
    latex/core/core.cpp \
    latex/core/formula.cpp \
    latex/core/formula_def.cpp \
    latex/core/localized_num.cpp \
    latex/core/macro.cpp \
    latex/core/macro_def.cpp \
    latex/core/macro_impl.cpp \
    latex/core/parser.cpp \
    latex/fonts/alphabet.cpp \
    latex/fonts/font_basic.cpp \
    latex/fonts/font_info.cpp \
    latex/fonts/fonts.cpp \
    latex/latex.cpp \
    latex/platform/qt/graphic_qt.cpp \
    latex/render.cpp \
    latex/res/builtin/formula_mappings.res.cpp \
    latex/res/builtin/glue.res.cpp \
    latex/res/builtin/symbol_mapping.res.cpp \
    latex/res/builtin/tex_param.res.cpp \
    latex/res/builtin/tex_symbols.res.cpp \
    latex/res/font/bi10.def.cpp \
    latex/res/font/bx10.def.cpp \
    latex/res/font/cmbsy10.def.cpp \
    latex/res/font/cmbx10.def.cpp \
    latex/res/font/cmbxti10.def.cpp \
    latex/res/font/cmex10.def.cpp \
    latex/res/font/cmmi10.def.cpp \
    latex/res/font/cmmi10_unchanged.def.cpp \
    latex/res/font/cmmib10.def.cpp \
    latex/res/font/cmmib10_unchanged.def.cpp \
    latex/res/font/cmr10.def.cpp \
    latex/res/font/cmss10.def.cpp \
    latex/res/font/cmssbx10.def.cpp \
    latex/res/font/cmssi10.def.cpp \
    latex/res/font/cmsy10.def.cpp \
    latex/res/font/cmti10.def.cpp \
    latex/res/font/cmti10_unchanged.def.cpp \
    latex/res/font/cmtt10.def.cpp \
    latex/res/font/dsrom10.def.cpp \
    latex/res/font/eufb10.def.cpp \
    latex/res/font/eufm10.def.cpp \
    latex/res/font/i10.def.cpp \
    latex/res/font/moustache.def.cpp \
    latex/res/font/msam10.def.cpp \
    latex/res/font/msbm10.def.cpp \
    latex/res/font/r10.def.cpp \
    latex/res/font/r10_unchanged.def.cpp \
    latex/res/font/rsfs10.def.cpp \
    latex/res/font/sb10.def.cpp \
    latex/res/font/sbi10.def.cpp \
    latex/res/font/si10.def.cpp \
    latex/res/font/special.def.cpp \
    latex/res/font/ss10.def.cpp \
    latex/res/font/stmary10.def.cpp \
    latex/res/font/tt10.def.cpp \
    latex/res/parser/font_parser.cpp \
    latex/res/parser/formula_parser.cpp \
    latex/res/reg/builtin_font_reg.cpp \
    latex/res/reg/builtin_syms_reg.cpp \
    latex/res/sym/amsfonts.def.cpp \
    latex/res/sym/amssymb.def.cpp \
    latex/res/sym/base.def.cpp \
    latex/res/sym/stmaryrd.def.cpp \
    latex/res/sym/symspecial.def.cpp \
    latex/xml/tinyxml2.cpp

HEADERS += \
    latex/samples/qt_texqmlitem.h \
    latex/samples/qt_texwidget.h \
    latex/atom/atom.h \
    latex/atom/atom_basic.h \
    latex/atom/atom_impl.h \
    latex/atom/box.h \
    latex/common.h \
    latex/config.h \
    latex/core/core.h \
    latex/core/formula.h \
    latex/core/macro.h \
    latex/core/macro_impl.h \
    latex/core/parser.h \
    latex/fonts/alphabet.h \
    latex/fonts/font_basic.h \
    latex/fonts/font_info.h \
    latex/fonts/font_reg.h \
    latex/fonts/fonts.h \
    latex/fonts/symbol_reg.h \
    latex/fonts/tex_font.h \
    latex/graphic/graphic.h \
    latex/graphic/graphic_basic.h \
    latex/latex.h \
    latex/platform/qt/graphic_qt.h \
    latex/render.h \
    latex/res/font_def.res.h \
    latex/res/parser/font_parser.h \
    latex/res/parser/formula_parser.h \
    latex/res/reg/builtin_font_reg.h \
    latex/res/reg/builtin_syms_reg.h \
    latex/res/symbol_def.res.h \
    latex/utils/constants.h \
    latex/utils/exceptions.h \
    latex/utils/indexed_arr.h \
    latex/utils/log.h \
    latex/utils/nums.h \
    latex/utils/string_utils.h \
    latex/utils/utf.h \
    latex/xml/tinyxml2.h

RESOURCES += latex.qrc
