name: Windows GDI+

on:
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
    steps:
    - name: Downloading Source Code 📥
      uses: actions/checkout@v2
    - name: Downloading CMake 📥
      # Install latest CMake.
      uses: lukka/get-cmake@latest
    - name: Setup Environment (x64)
      uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: x64
    - name: Configure 🔧
      run: |
        cd ${{ github.workspace }}
        mkdir build -force
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DHAVE_AUTO_FONT_FIND=OFF -DGDI=ON -DBUILD_EXAMPLE_WIN32=ON -G Ninja
    - name: Compile 🎲
      run: |
        cd ${{ github.workspace }}
        cd build
        ninja