name: Windows GDI+

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: 
          - windows-2019
    steps:
    - name: Downloading Source Code 📥
      uses: actions/checkout@v2
    - name: Downloading CMake 📥
      # Install latest CMake.
      uses: lukka/get-cmake@latest
    - name: Downloading Vcpkg 📥
      run: |
        cd ${{ github.workspace }}
        mkdir build -force
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
    - name: Setup Environment (x64)
      uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
      with:
        arch: x64
    - name: Configure 🔧
      run: |
        cd ${{ github.workspace }}
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -G Ninja
    - name: Compile 🎲
      run: |
        cd ${{ github.workspace }}
        cd build
        ninja